package Interfaces;


public class ChangeCars extends javax.swing.JDialog {

    /**
     * Creates new form ChangeCars
     */
    public ChangeCars(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        lblSubtitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle1 = new javax.swing.JLabel();
        pnlFooter = new javax.swing.JPanel();
        studentsName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlHeader1 = new javax.swing.JPanel();
        pnlFooter1 = new javax.swing.JPanel();
        studentsName1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setBackground(new java.awt.Color(103, 12, 43));
        pnlHeader.setForeground(new java.awt.Color(153, 0, 51));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubtitle.setFont(new java.awt.Font("Lao MN", 2, 36)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setText("Enterprise");
        pnlHeader.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, 90));

        lblTitle.setFont(new java.awt.Font("Lao MN", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Car");
        pnlHeader.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 90, 60));

        lblSubtitle1.setFont(new java.awt.Font("Lao MN", 1, 48)); // NOI18N
        lblSubtitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle1.setText("Cambio de Carros");
        pnlHeader.add(lblSubtitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 430, 90));

        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        pnlFooter.setBackground(new java.awt.Color(103, 12, 43));
        pnlFooter.setForeground(new java.awt.Color(153, 0, 51));
        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsName.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        studentsName.setForeground(new java.awt.Color(255, 255, 255));
        studentsName.setText("Murillo Anchia Pamela");
        pnlFooter.add(studentsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1100, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 550));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, -1, -1));

        pnlHeader1.setBackground(new java.awt.Color(103, 12, 43));
        pnlHeader1.setForeground(new java.awt.Color(153, 0, 51));
        pnlHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 130));

        pnlFooter1.setBackground(new java.awt.Color(103, 12, 43));
        pnlFooter1.setForeground(new java.awt.Color(153, 0, 51));
        pnlFooter1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsName1.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        studentsName1.setForeground(new java.awt.Color(255, 255, 255));
        studentsName1.setText("Murillo Anchia Pamela");
        pnlFooter1.add(studentsName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        getContentPane().add(pnlFooter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1100, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeCars.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangeCars dialog = new ChangeCars(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblSubtitle1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlFooter1;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHeader1;
    private javax.swing.JLabel studentsName;
    private javax.swing.JLabel studentsName1;
    // End of variables declaration//GEN-END:variables
}
