/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author pamelamurillo
 */
public class LoginFrame extends javax.swing.JFrame {

    private String defaultUsernameText = "Indique aquí su nombre";
    private String defaultPasswordText = "*********";
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        btnLogin.setOpaque(true);
        btnRegister.setOpaque(true);
    }

    
    public void resetLabels() {
        lblErrorUser.setVisible(false);
        lblErrorPassword.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSide = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubtitle = new javax.swing.JLabel();
        pnlMainBackground = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        lblErrorUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        lblErrorPassword = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlHeader = new javax.swing.JPanel();
        pnlFooter = new javax.swing.JPanel();
        studentsName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(153, 0, 51));
        pnlSide.setForeground(new java.awt.Color(153, 0, 51));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Lao MN", 1, 70)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Car");
        pnlSide.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 90));

        lblSubtitle.setFont(new java.awt.Font("Lao MN", 2, 48)); // NOI18N
        lblSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSubtitle.setText("Enterprise");
        pnlSide.add(lblSubtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 90));

        getContentPane().add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 550));

        pnlMainBackground.setBackground(new java.awt.Color(255, 255, 255));
        pnlMainBackground.setForeground(new java.awt.Color(255, 255, 255));
        pnlMainBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsername.setFont(new java.awt.Font("Kohinoor Bangla", 0, 17)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 0));
        lblUsername.setText("Nombre de Usuario");
        pnlMainBackground.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        inputUsername.setBackground(new java.awt.Color(245, 245, 245));
        inputUsername.setFont(new java.awt.Font("Kohinoor Bangla", 2, 15)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(102, 102, 102));
        inputUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputUsername.setText("Indique aquí su nombre");
        inputUsername.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        inputUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputUsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputUsernameMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputUsernameMouseEntered(evt);
            }
        });
        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });
        pnlMainBackground.add(inputUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 250, 40));

        lblErrorUser.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorUser.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorUser.setText("Nombre de usuario no válido");
        pnlMainBackground.add(lblErrorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        pnlMainBackground.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, 10));

        lblPassword.setFont(new java.awt.Font("Kohinoor Bangla", 0, 17)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 0));
        lblPassword.setText("Contraseña");
        pnlMainBackground.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        inputPassword.setBackground(new java.awt.Color(245, 245, 245));
        inputPassword.setFont(new java.awt.Font("Kohinoor Bangla", 1, 15)); // NOI18N
        inputPassword.setForeground(new java.awt.Color(102, 102, 102));
        inputPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputPassword.setText("*********");
        inputPassword.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        inputPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputPasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inputPasswordMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inputPasswordMouseEntered(evt);
            }
        });
        pnlMainBackground.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 250, 40));

        lblErrorPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorPassword.setForeground(new java.awt.Color(204, 0, 0));
        lblErrorPassword.setText("La contraseña no es válida para este nombre de usuario");
        pnlMainBackground.add(lblErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));
        pnlMainBackground.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 250, 10));

        jLabel1.setFont(new java.awt.Font("Lao MN", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("Inicio de sesión");
        pnlMainBackground.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 30));

        btnRegister.setBackground(new java.awt.Color(153, 0, 51));
        btnRegister.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrarse");
        btnRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlMainBackground.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 160, 50));

        btnLogin.setBackground(new java.awt.Color(153, 0, 51));
        btnLogin.setFont(new java.awt.Font("Lao MN", 1, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar Sesión");
        btnLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlMainBackground.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 160, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces/carIcon.png"))); // NOI18N
        pnlMainBackground.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 350, 390));

        getContentPane().add(pnlMainBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 790, 550));

        pnlHeader.setBackground(new java.awt.Color(103, 12, 43));
        pnlHeader.setForeground(new java.awt.Color(153, 0, 51));
        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 130));

        pnlFooter.setBackground(new java.awt.Color(103, 12, 43));
        pnlFooter.setForeground(new java.awt.Color(153, 0, 51));
        pnlFooter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentsName.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        studentsName.setForeground(new java.awt.Color(255, 255, 255));
        studentsName.setText("Murillo Anchia Pamela");
        pnlFooter.add(studentsName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        getContentPane().add(pnlFooter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 1090, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void inputUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseClicked
        resetLabels();

    }//GEN-LAST:event_inputUsernameMouseClicked

    private void inputUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseExited
        if ( inputUsername.getText().equals("") ) {
            inputUsername.setText(defaultUsernameText);
        }
    }//GEN-LAST:event_inputUsernameMouseExited

    private void inputUsernameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsernameMouseEntered
        if ( inputUsername.getText().equals(defaultUsernameText) ) {
            inputUsername.setText("");
        }
    }//GEN-LAST:event_inputUsernameMouseEntered

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void inputPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseClicked
        resetLabels();

    }//GEN-LAST:event_inputPasswordMouseClicked

    private void inputPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseExited
        if ( String.valueOf(inputPassword.getPassword()).equals("") ) {
            inputPassword.setText(defaultPasswordText);
        }
    }//GEN-LAST:event_inputPasswordMouseExited

    private void inputPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputPasswordMouseEntered
        if ( String.valueOf(inputPassword.getPassword()).equals(defaultPasswordText) ) {
            inputPassword.setText("");
        }
    }//GEN-LAST:event_inputPasswordMouseEntered

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSubtitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMainBackground;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JLabel studentsName;
    // End of variables declaration//GEN-END:variables
}
